#include "dominion.h"
#include "asserttrue.h"
#include <stdio.h>

int main () {
	printf("\n******************************************************************************************\n");
	printf("                                 UNIT TEST 4: Tribute Card                                \n");
	printf("******************************************************************************************\n");
	struct gameState testState;
	int k[10] = { adventurer, gardens, embargo, village, minion, mine, cutpurse,
		 sea_hag, tribute, curse };
	printf("\n------------------------------------------------------------------------------------------\n");
	printf("                                ONE OR LESS CARDS ASSERTIONS                              \n");
	printf("------------------------------------------------------------------------------------------\n");
	printf("TESTING SINGLE ACTION CARD IN PLAYER 2 DECK\n");
	initializeGame(4, k, 30, &testState);
	testState.numActions = 0;
	testState.coins = 0;
	testState.handCount[0] = 0;
	testState.handCount[1] = 0;
	testState.deckCount[1] = 1;
	testState.deck[1][0] = ambassador;
	testState.deck[1][1] = -1;
	tributeCard(&testState, 0, 1);
	printf("Player 1 should have +2 actions: <Result = %i> ", testState.numActions);
	asserttrue(testState.numActions == 2, 1);
	printf("Player 1 should have 0 coins: <Result = %i> ", testState.coins);
	asserttrue(testState.coins == 0, 1);
	printf("Player 1 should have 0 cards in hand: <Result = %i> ", testState.handCount[0]);
	asserttrue(testState.handCount[0] == 0, 1);
	printf("Player 2 should have 1 card in discard: <Result = %i> ", testState.discardCount[1]);
	asserttrue(testState.discardCount[1] == 1, 1);
	printf("Player 2 should have 0 cards in deck: <Result = %i> ", testState.deckCount[1]);
	asserttrue(testState.deckCount[1] == 0, 1);
	printf("\nTESTING SINGLE TREASURE CARD IN PLAYER 2 DECK\n");
	initializeGame(4, k, 30, &testState);
	testState.numActions = 0;
	testState.coins = 0;
	testState.handCount[0] = 0;
	testState.handCount[1] = 0;
	testState.deckCount[1] = 1;
	testState.deck[1][0] = copper;
	testState.deck[1][1] = -1;
	tributeCard(&testState, 0, 1);
	printf("Player 1 should have 0 actions: <Result = %i> ", testState.numActions);
	asserttrue(testState.numActions == 0, 1);
	printf("Player 1 should have +2 coins: <Result = %i> ", testState.coins);
	asserttrue(testState.coins == 2, 1);
	printf("Player 1 should have 0 cards in hand: <Result = %i> ", testState.handCount[0]);
	asserttrue(testState.handCount[0] == 0, 1);
	printf("Player 2 should have 1 card in discard: <Result = %i> ", testState.discardCount[1]);
	asserttrue(testState.discardCount[1] == 1, 1);
	printf("Player 2 should have 0 cards in deck: <Result = %i> ", testState.deckCount[1]);
	asserttrue(testState.deckCount[1] == 0, 1);
	printf("\nTESTING SINGLE VICTORY CARD IN PLAYER 2 DECK\n");
	initializeGame(4, k, 30, &testState);
	testState.numActions = 0;
	testState.coins = 0;
	testState.handCount[0] = 0;
	testState.handCount[1] = 0;
	testState.deckCount[1] = 1;
	testState.deck[1][0] = estate;
	testState.deck[1][1] = -1;
	tributeCard(&testState, 0, 1);
	printf("Player 1 should have 0 actions: <Result = %i> ", testState.numActions);
	asserttrue(testState.numActions == 0, 1);
	printf("Player 1 should have 0 coins: <Result = %i> ", testState.coins);
	asserttrue(testState.coins == 0, 1);
	printf("Player 1 should have +2 cards in hand: <Result = %i> ", testState.handCount[0]);
	asserttrue(testState.handCount[0] == 2, 1);
	printf("Player 2 should have 1 card in discard: <Result = %i> ", testState.discardCount[1]);
	asserttrue(testState.discardCount[1] == 1, 1);
	printf("Player 2 should have 0 cards in deck: <Result = %i> ", testState.deckCount[1]);
	asserttrue(testState.deckCount[1] == 0, 1);
	printf("\nTESTING NO CARDS\n");
	initializeGame(4, k, 30, &testState);
	testState.numActions = 0;
	testState.coins = 0;
	testState.handCount[0] = 0;
	testState.handCount[1] = 0;
	testState.deckCount[1] = 0;
	testState.discardCount[1] = 0;
	tributeCard(&testState, 0, 1);
	printf("Player 1 should have 0 actions: <Result = %i> ", testState.numActions);
	asserttrue(testState.numActions == 0, 1);
	printf("Player 1 should have 0 coins: <Result = %i> ", testState.coins);
	asserttrue(testState.coins == 0, 1);
	printf("Player 1 should have 0 cards in hand: <Result = %i> ", testState.handCount[0]);
	asserttrue(testState.handCount[0] == 0, 1);
	printf("Player 2 should have 1 card in discard: <Result = %i> ", testState.discardCount[1]);
	asserttrue(testState.discardCount[1] == 1, 1);
	printf("Player 2 should have 0 cards in deck: <Result = %i> ", testState.deckCount[1]);
	asserttrue(testState.deckCount[1] == 0, 1);
	printf("\nTESTING SINGLE CARD IN PLAYER 2 DISCARD\n");
	/*initializeGame(4, k, 30, &testState);
	testState.numActions = 0;
	testState.coins = 0;
	testState.handCount[0] = 0;
	testState.handCount[1] = 0;
	testState.deckCount[1] = 0;
	testState.discardCount[1] = 1;
	testState.discard[1][0] = copper;
	testState.discard[1][1] = -1;
	tributeCard(&testState, 0, 1);
	printf("Player 1 should have 0 actions: <Result = %i> ", testState.numActions);
	asserttrue(testState.numActions == 0, 1);
	printf("Player 1 should have +2 coins: <Result = %i> ", testState.coins);
	asserttrue(testState.coins == 2, 1);
	printf("Player 1 should have 0 cards in hand: <Result = %i> ", testState.handCount[0]);
	asserttrue(testState.handCount[0] == 0, 1);
	printf("Player 2 should have 1 card in discard: <Result = %i> ", testState.discardCount[1]);
	asserttrue(testState.discardCount[1] == 1, 1);
	printf("Player 2 should have 0 cards in deck: <Result = %i> ", testState.deckCount[1]);
	asserttrue(testState.deckCount[1] == 0, 1);*/
	printf("\n------------------------------------------------------------------------------------------\n");
	printf("                                TWO OR MORE CARDS ASSERTIONS                              \n");
	printf("------------------------------------------------------------------------------------------\n");
	printf("\nTESTING ONE CARD IN DECK + ONE CARD IN DISCARD\n");
	initializeGame(4, k, 30, &testState);
	testState.numActions = 0;
	testState.coins = 0;
	testState.handCount[0] = 0;
	testState.handCount[1] = 0;
	testState.deckCount[1] = 1;
	testState.deck[1][0] = copper;
	testState.discardCount[1] = 1;
	testState.discard[1][0] = silver;
	tributeCard(&testState, 0, 1);
	printf("Player 1 should have 0 actions: <Result = %i> ", testState.numActions);
	asserttrue(testState.numActions == 0, 1);
	printf("Player 1 should have +4 coins: <Result = %i> ", testState.coins);
	asserttrue(testState.coins == 4, 1);
	printf("Player 1 should have 0 cards in hand: <Result = %i> ", testState.handCount[0]);
	asserttrue(testState.handCount[0] == 0, 1);
	printf("Player 2 should have 2 cards in discard: <Result = %i> ", testState.discardCount[1]);
	asserttrue(testState.discardCount[1] == 2, 1);
	printf("Player 2 should have 0 cards in deck: <Result = %i> ", testState.deckCount[1]);
	asserttrue(testState.deckCount[1] == 0, 1);
	printf("\nTESTING TWO CARDS IN DECK\n");
	initializeGame(4, k, 30, &testState);
	testState.numActions = 0;
	testState.coins = 0;
	testState.handCount[0] = 0;
	testState.handCount[1] = 0;
	testState.deckCount[1] = 2;
	testState.deck[1][0] = copper;
	testState.deck[1][1] = copper;
	testState.discardCount[1] = 0;
	tributeCard(&testState, 0, 1);
	printf("Player 1 should have 0 actions: <Result = %i> ", testState.numActions);
	asserttrue(testState.numActions == 0, 1);
	printf("Player 1 should have +4 coins: <Result = %i> ", testState.coins);
	asserttrue(testState.coins == 4, 1);
	printf("Player 1 should have 0 cards in hand: <Result = %i> ", testState.handCount[0]);
	asserttrue(testState.handCount[0] == 0, 1);
	printf("Player 2 should have 2 cards in discard: <Result = %i> ", testState.discardCount[1]);
	asserttrue(testState.discardCount[1] == 2, 1);
	printf("Player 2 should have 0 cards in deck: <Result = %i> ", testState.deckCount[1]);
	asserttrue(testState.deckCount[1] == 0, 1);
	printf("\n\n");
	return 0;
}
