CFLAGS= -Wall -fpic -coverage -lm -std=c99

rngs.o: rngs.h rngs.c
	gcc -c rngs.c -g  $(CFLAGS)

dominion.o: dominion.h dominion.c rngs.o
	gcc -c dominion.c -g  $(CFLAGS)

playdom: dominion.o playdom.c
	gcc -o playdom playdom.c -g dominion.o rngs.o $(CFLAGS)
#To run playdom you need to entere: ./playdom <any integer number> like ./playdom 10*/
testDrawCard: testDrawCard.c dominion.o rngs.o
	gcc  -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

badTestDrawCard: badTestDrawCard.c dominion.o rngs.o
	gcc -o badTestDrawCard -g  badTestDrawCard.c dominion.o rngs.o $(CFLAGS)

testBuyCard: testDrawCard.c dominion.o rngs.o
	gcc -o testDrawCard -g  testDrawCard.c dominion.o rngs.o $(CFLAGS)

testAll: dominion.o testSuite.c
	gcc -o testSuite testSuite.c -g  dominion.o rngs.o $(CFLAGS)

interface.o: interface.h interface.c
	gcc -c interface.c -g  $(CFLAGS)

runtests: testDrawCard 
	./testDrawCard &> unittestresult.out
	gcov dominion.c >> unittestresult.out
	cat dominion.c.gcov >> unittestresult.out


player: player.c interface.o
	gcc -o player player.c -g  dominion.o rngs.o interface.o $(CFLAGS)

unittest1: unittest1.c dominion.o rngs.o asserttrue.o dominion_helpers.h
	gcc -o unittest1 -g  unittest1.c dominion.o rngs.o asserttrue.o $(CFLAGS)

unittest2: unittest2.c dominion.o rngs.o asserttrue.o dominion_helpers.h
	gcc -o unittest2 -g  unittest2.c dominion.o rngs.o asserttrue.o $(CFLAGS)

unittest3: unittest3.c dominion.o rngs.o asserttrue.o dominion_helpers.h
	gcc -o unittest3 -g  unittest3.c dominion.o rngs.o asserttrue.o $(CFLAGS)

unittest4: unittest4.c dominion.o rngs.o asserttrue.o dominion_helpers.h
	gcc -o unittest4 -g  unittest4.c dominion.o rngs.o asserttrue.o $(CFLAGS)

unittest5: unittest5.c dominion.o rngs.o asserttrue.o dominion_helpers.h
	gcc -o unittest5 -g  unittest5.c dominion.o rngs.o asserttrue.o $(CFLAGS)

randomtestcard1: randomtestcard1.c dominion.o rngs.o asserttrue.o dominion_helpers.h
	gcc -o randomtestcard1 -g  randomtestcard1.c dominion.o rngs.o asserttrue.o $(CFLAGS)

randomtestcard2: randomtestcard2.c dominion.o rngs.o asserttrue.o dominion_helpers.h
	gcc -o randomtestcard2 -g  randomtestcard2.c dominion.o rngs.o asserttrue.o $(CFLAGS)

randomtestcard3: randomtestcard3.c dominion.o rngs.o asserttrue.o dominion_helpers.h
	gcc -o randomtestcard3 -g  randomtestcard3.c dominion.o rngs.o asserttrue.o $(CFLAGS)

unittestresults:
	gcc -o unittest1 dominion.c rngs.c unittest1.c asserttrue.c $(CFLAGS)
	unittest1 >> unittestresults.out
	gcov dominion.c -b -f >> unittestresults.out
	gcc -o unittest2 dominion.c rngs.c unittest2.c asserttrue.c $(CFLAGS)
	unittest2 >> unittestresults.out
	gcov dominion.c -b -f >> unittestresults.out
	gcc -o unittest3 dominion.c rngs.c unittest3.c asserttrue.c $(CFLAGS)
	unittest3 >> unittestresults.out
	gcov dominion.c -b -f >> unittestresults.out
	gcc -o unittest4 dominion.c rngs.c unittest4.c asserttrue.c $(CFLAGS)
	unittest4 >> unittestresults.out
	gcov dominion.c -b -f >> unittestresults.out
	gcc -o unittest5 dominion.c rngs.c unittest5.c asserttrue.c $(CFLAGS)
	unittest5 >> unittestresults.out
	gcov dominion.c -b -f >> unittestresults.out
	gcc -o randomtestcard1 dominion.c rngs.c randomtestcard1.c asserttrue.c $(CFLAGS)
	randomtestcard1 >> randomtestresults.out
	gcov dominion.c -b -f >> randomtestresults.out
	gcc -o randomtestcard2 dominion.c rngs.c randomtestcard2.c asserttrue.c $(CFLAGS)
	randomtestcard2 >> randomtestresults.out
	gcov dominion.c -b -f >> randomtestresults.out
	gcc -o randomtestcard3 dominion.c rngs.c randomtestcard3.c asserttrue.c $(CFLAGS)
	randomtestcard3 >> randomtestresults.out
	gcov dominion.c -b -f >> randomtestresults.out

all: playdom player 

clean:
	rm -f *.o playdom.exe playdom player player.exe  *.gcov *.gcda *.gcno *.so *.out testDrawCard testDrawCard.exe
